#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1535605917                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Stay active, stay healthy.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bogdan Dovgopol
your_link                                 : https://twitter.com/_thedov             
your_city                                 : Sydney, 🇦🇺
email_address                             : info@mypedometer.app
facebook_username                         :                 
instagram_username                        :
twitter_username                          : MyPedometerApp
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Step counts
    description                           : Track your daily step counts.
    fontawesome_icon_name                 : walking
    
  - title                                 : Flights climbed
    description                           : Track how many stairs you've climbed.
    fontawesome_icon_name                 : arrow-up

  - title                                 : Walking distance
    description                           : Track how far you've walked.
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : Walking speed
    description                           : Track your average walking speed.
    fontawesome_icon_name                 : bolt

  - title                                 : Heart Rate
    description                           : Track your heart beat rate.
    fontawesome_icon_name                 : heartbeat
  
  - title                                 : Blood oxygen 
    description                           : Track your blood saturation level.
    fontawesome_icon_name                 : tint

#   - title                                 : Smart App Banner
#     description                           : Display a smart app banner on iOS devices.
#     fontawesome_icon_name                 : arrow-alt-circle-down

#   - title                                 : Social Links
#     description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : link

#   - title                                 : FontAwesome Support
#     description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : info-circle

#   - title                                 : # New Feature Title
#     description                           : # New Feature Description
#     fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#33C759"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

cover_image                               :                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#33C759"

app_title_color                           : "#1C1C1E"
app_price_color                           : "#1C1C1E"
app_description_color                     : "#1C1C1E"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#33C759"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/
    
# Markdown rendering 
markdown: kramdown
